/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id:
    'us-west-2:f28348c1-0ae0-4fbc-a502-09dfa0f305ec',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_csf3qSlAY',
  aws_user_pools_web_client_id: '19pn1pc2vg649nhh9hbqri49a5',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://pn3oqfekjjgpxdenfr4d4hc3yq.appsync-api.us-west-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-west-2',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
}

export default awsmobile
